cliente:
    confiable:
        # Configuración específica por tipo de cliente
        tipos:
            INDIVIDUAL:
                antiguedad:
                    medicion: MES       # Unidad de medición de antigüedad: DIA, SEMANA, MES, AÑO
                    minimo-medicion: 24 # Valor mínimo para considerar al cliente confiable (ej: 24 meses)
                perfiles-no-confiables:
                    - IRRECUPERABLE     # Perfiles de cliente no confiable
                limite-chargeback: 0  # Máximo de chargebacks permitidos para ser considerado confiable

            COMPANY:
                antiguedad:
                    medicion: MES
                    minimo-medicion: 12       # Las empresas necesitan mayor antigüedad para ser confiables
                perfiles-no-confiables:
                    - CRITICO                  # Perfiles de empresa no confiable
                limite-chargeback: 0      # Empresas pueden tener hasta 2 chargebacks y seguir siendo confiables



velocity-transaction-params:
    individuo:
        minutes-range: 10
        max-transactions: 5
        min-monto: 10000
        max-monto: 50000
    empresa:
        minutes-range: 10
        max-transactions: 20
        min-monto: 150000
        max-monto: 400000

transaction:
    frequency:
        client:
            individual:
                check-window-hs: 24 # Ventana de tiempo en horas para verificar la frecuencia de transacciones
                max-transfers-same-beneficiary: 3 # Máximo de transferencias al mismo beneficiario
                max-deposits-account-holder: 5 # Máximo de depósitos al titular de la cuenta
                types-account-holder: # Tipos de cuentas que entran en la verificación de frecuencia
                    - CUENTA_CORRIENTE
                    - CUENTA_AHORRO
                    - CUENTA_PLAZO_FIJO
                    - CUENTA_INVERSION
            company:
                check-window-hs: 24 # Ventana de tiempo en horas para verificar
                max-transfers-same-beneficiary: 5 # Máximo de transferencias al mismo beneficiario
                max-deposits-account-holder: 10 # Máximo de depósitos al titular de la
                types-account-holder: # Tipos de cuentas que entran en la verificación de frecuencia
                    - CUENTA_CORRIENTE
                    - CUENTA_AHORRO
                    - CUENTA_PLAZO_FIJO
                    - CUENTA_INVERSION

alert:
    thresholds:
        INDIVIDUAL: 2.0   # 200% del promedio histórico
        COMPANY: 3.0      # 300% del promedio histórico
