cliente:
    confiable:
        antiguedad:
            medicion: MES       # MES, AÑO, DIA, SEMANA
            minimo-medicion: 24          # Número entero o decimal (ej: 18, 1.5)
        perfiles-no-confiables:
            - IRRECUPERABLE     # Perfiles del cliente no confiable
        limite-chargeback: 0

velocity-transaction-params:
    individuo:
        minutes-range: 10
        max-transactions: 5
    empresa:
        minutes-range: 10
        max-transactions: 20

transferencias:
  internacionales:
    paises-riesgo:
      - Venezuela
      - Rusia
      - Iran
    monto-alerta: 50000.00