cliente:
    confiable:
        antiguedad:
            medicion: MES       # MES, AÑO, DIA, SEMANA
            minimo-medicion: 24          # Número entero o decimal (ej: 18, 1.5)
        perfiles-no-confiables:
            - IRRECUPERABLE     # Perfiles del cliente no confiable
        limite-chargeback: 0

velocity-transaction-params:
    individuo:
        minutes-range: 10
        max-transactions: 5
    empresa:
        minutes-range: 10
        max-transactions: 20

transaction:
    frequency:
        client:
            individual:
                check-window-hs: 24 # Ventana de tiempo en horas para verificar la frecuencia de transacciones
                max-transfers-same-beneficiary: 3 # Máximo de transferencias al mismo beneficiario
                max-deposits-account-holder: 5 # Máximo de depósitos al titular de la cuenta
                types-account-holder: # Tipos de cuentas que entran en la verificación de frecuencia
                    - CUENTA_CORRIENTE
                    - CUENTA_AHORRO
                    - CUENTA_PLAZO_FIJO
                    - CUENTA_INVERSION
            company:
                check-window-hs: 24 # Ventana de tiempo en horas para verificar
                max-transfers-same-beneficiary: 5 # Máximo de transferencias al mismo beneficiario
                max-deposits-account-holder: 10 # Máximo de depósitos al titular de la
                types-account-holder: # Tipos de cuentas que entran en la verificación de frecuencia
                    - CUENTA_CORRIENTE
                    - CUENTA_AHORRO
                    - CUENTA_PLAZO_FIJO
                    - CUENTA_INVERSION
